//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUIZApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuizAppDBEntities1 : DbContext
    {
        public QuizAppDBEntities1()
            : base("name=QuizAppDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<SetExam> SetExams { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Tbl_Questions> Tbl_Questions { get; set; }
    }
}
