//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUIZApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetExam
    {
        public int ExamId { get; set; }
        public System.DateTime ExamDate { get; set; }
        public int Std_Id { get; set; }
        public string ExamName { get; set; }
        public int Score { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
