//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QUIZApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Questions
    {
        public int Q_Id { get; set; }
        public string Q_Text { get; set; }
        public string OPA { get; set; }
        public string OPB { get; set; }
        public string OPC { get; set; }
        public string OPD { get; set; }
        public string COP { get; set; }
        public int Cat_Id { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
